name: Shell commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    steps:
      - name: echo a string
<<<<<<< HEAD
        run: echo "Hello world"
=======
        run: echo "Hello world"
>>>>>>> 3c379f4cdadfd26f62d9e5697c829ed1f05bffb5
      - name: multiline script
        run: |
          python3 -V
          touch my_file_with_workflow.py
          ls -l
